### ISSUE TITLE
Раздача добавляется через скрипт gettorrensbyrss.py, но не загружается

### ISSUE THREAD

**Issue by Leliil** [tarampampam/scripts#1]
Скрипт работает, файл добавляется в трансмиссию, но не скачивается, пишет: Трекер: Could not connect to tracker
Если добавлять вручную - все работает.
/etc/resolv.conf - там выставлен ip роутера

**Comment by tarampampam** [comment]
О каком скрипте идет речь?

**Comment by Leliil** [comment]
gettorrensbyrss.py

**Comment by tarampampam** [comment]
Рядом лежит `get_torrents.sh` - его пробовал?
